---
title: "Example Graph"
author: "Adam Edwards"
date: "October 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(networkD3)
library(igraph)

# Load data
nodes <- read.csv("data/win1997_node_list.txt", header = TRUE)
edges <- read.csv("data/win1997_edge_list.txt", header = TRUE)
```

## Example Graph -- Winter 1997

```{r graph, echo=FALSE}

# Create Graphs

gg <- graph_from_edgelist(matrix(unlist(lapply(edges, as.character)), ncol = 2, byrow = TRUE), directed = TRUE)

members <- membership(cluster_optimal(gg))

btwn <- betweenness(gg, v = V(gg), directed = TRUE)

graph_d3 <- igraph_to_networkD3(gg,group = members)

graph_d3$nodes$degree <- as.character(degree(gg, v = V(gg))*5)

# Plot
forceNetwork(Links = graph_d3$links,
             Nodes = graph_d3$nodes,
             Source = "source",
             Target = "target",
             Group = "group",
             height = 800,
             width = 800,
             NodeID = "name", 
             Nodesize = "degree",
             arrows = FALSE,
             opacity = 0.8,
             fontFamily = "sans-serif",
             fontSize = 14,
             zoom = TRUE)
```
